apiVersion: v2
name: envoy-gateway-crds
version: 1.0.0

sources:
  - https://github.com/envoyproxy/gateway

dependencies:
  - name: gateway-crds-helm
    version: 1.9.1
    repository: oci://docker.io/envoyproxy
