ntfy:
  image:
    tag: "v2.13.0"
  ntfy:
    baseURL: "https://ntfy.obara.dev"
    enableReservations: false
    enableSignup: true
    enableLogin: true

  persistence:
    enabled: true

  prometheus:
    servicemonitor:
      enabled: false

  grafana:
    dashboards:
      enabled: false

  ingress:
    enabled: false

