apiVersion: v2
name: bytestash
version: 1.0.0

sources:
  - https://github.com/jordan-dalby/ByteStash

dependencies:
  - name: app-template
    repository: oci://ghcr.io/bjw-s-labs/helm
    version: 5.2.1
    alias: bytestash