{{- range .Values.clusterSecretStores }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  provider:
    {{- toYaml .provider | nindent 6 }}
{{- end }}