apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: universal-auth-credentials
  namespace: external-secrets
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: external-secrets/infisical
        metadataPolicy: None
        property: clientId
      secretKey: clientId
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: external-secrets/infisical
        metadataPolicy: None
        property: clientSecret
      secretKey: clientSecret
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-cluster-secret-store
  target:
    name: universal-auth-credentials