apiVersion: v2
name: scribblers
version: 1.0.0

sources:
  - https://github.com/scribble-rs/scribble.rs

dependencies:
  - name: app-template
    repository: oci://ghcr.io/bjw-s-labs/helm
    version: 5.2.1
    alias: scribblers
