---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud-obara-dev-tls
spec:
  secretName: cloud-obara-dev-tls
  issuerRef:
    name: letsencrypt-private-key
    kind: ClusterIssuer
  commonName: "*.cloud.obara.dev"
  dnsNames:
  - "*.cloud.obara.dev"