---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: kube-system
spec:
  encryptedData:
    cloudflare-token: AgBrT3iPtvIGPi9bDco6t9lK1hHkihjfPflMk6pnfZUJxEz0lNRGkSySCpZekCMWOCz8hKUW3LI1+dzyAwhF4vmRAM+SHR4PSLKwtBc4W/PNo+6wSya4Wzhp0O1494WrS5fhGONZn/rFtzlV+9JxOnYIbdslt3wNJdPH9beZMjTQY5Q55ACj4sYsmc9aReR9Jd2MowMbYfJ7tpnidJI+zrDbKLMRdr+3Wws0YVuCPVn09fAJJUgcdtpxgkUyexSzjz0APFfkDKlk/a/qfXVP79xsSQRprGlW3E8SXC1Cwds2t0rz5ksel/lv0hTy/Kxuk1MTxL9oeiHMcQ1x5+aTBkggfWXkgz2KHQXFr+OclAzRW3hqieIzmmgjAUUa7WB7f3NOGaw5pgCaA7k0CakJLSvKfZ1tWHMaPz96Jnq1Gsj53exybNZvSIcCeOIxYLfuXWxrVwyuuk9VdYuO3/1Dy9REtMvZSfcmtyWWHNQpQxOa7RPJPeu5RSsjeuM0Ud1wQrdrP71jevobZp9PkRjPhqBgi2BbepRJaymx1SbahFKP4IB/T9P9zcj0cTDVVgCy80yho7y++Mg2W3TY2oFB97J6CJfWh31/vNAnvX00f+jDwBcHjTVVHX1sTK2HWcF+zBcWioFbNDiF8+1oejR1xi5sfSzyAruUn/JP3wqtdFWhs5YCN04URRb+laCJWSupQjwiMOHkd5S9G+I+2QC4ZOTl1mpiy27Py9W/bU9urPcCl6cJT82EDOyW
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: kube-system