apiVersion: v2
name: gitea-mirror
version: 1.0.0

sources:
  - https://github.com/RayLabsHQ/gitea-mirror

dependencies:
  - name: app-template
    repository: oci://ghcr.io/bjw-s-labs/helm
    version: 5.2.1
    alias: gitea-mirror
