gitea-mirror:
  defaultPodOptions:
    securityContext:
      fsGroup: 1001

  controllers:
    gitea-mirror:
      strategy: Recreate
      containers:
        main:
          image:
            repository: ghcr.io/raylabshq/gitea-mirror
            tag: 'v3.40.1'
            pullPolicy: IfNotPresent
          env:
            BETTER_AUTH_URL: "https://forgejo-mirror.cloud.obara.xyz"
            ENCRYPTION_SECRET:
              valueFrom:
                secretKeyRef:
                  name: gitea-mirror-secrets
                  key: ENCRYPTION_SECRET
            BETTER_AUTH_SECRET:
              valueFrom:
                secretKeyRef:
                  name: gitea-mirror-secrets
                  key: BETTER_AUTH_SECRET
  service:
    gitea-mirror:
      controller: gitea-mirror
      ports:
        http:
          port: 4321

  ingress:
    gitea-mirror:
      enabled: false

  persistence:
    data:
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 300Mi
      globalMounts:
        - path: /app/data

externalSecrets:
  secretStoreRef:
    name: oracle-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: gitea-mirror-secrets
  data:
  - secretKey: ENCRYPTION_SECRET
    remoteRef:
      key: development/gitea-mirror
      property: ENCRYPTION_SECRET
  - secretKey: BETTER_AUTH_SECRET
    remoteRef:
      key: development/gitea-mirror
      property: BETTER_AUTH_SECRET
