apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud-obara-xyz-tls
  namespace: envoy-gateway-system
spec:
  secretName: cloud-obara-xyz-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.cloud.obara.xyz"
  dnsNames:
    - "*.cloud.obara.xyz"
