{{- range list "homepage" "postgresus" "gitea-mirror" "openbao" "longhorn" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-{{ . }}-externalsecrets
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: oracle-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-{{ . }}-secret
  data:
    - secretKey: client-id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: cluster/oauth2-proxy-{{ . }}
        property: client-id
    - secretKey: client-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: cluster/oauth2-proxy-{{ . }}
        property: client-secret
    - secretKey: cookie-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: cluster/oauth2-proxy-{{ . }}
        property: cookie-secret
---
{{- end }}
