apiVersion: v2
name: postgresus
version: 1.0.0

sources:
  - https://github.com/databasus/databasus

dependencies:
  - name: app-template
    repository: oci://ghcr.io/bjw-s-labs/helm
    version: 5.2.1
    alias: postgresus
