postgresus:
  controllers:
    postgresus:
      strategy: Recreate
      containers:
        main:
          image:
            repository: databasus/databasus
            tag: v3.58.0
            pullPolicy: IfNotPresent
          env:
            - name: IS_DISABLE_CLOUD_NOTICE
              value: true

  service:
    postgresus:
      controller: postgresus
      ports:
        http:
          port: 4005

  ingress:
    postgresus:
      enabled: false

  persistence:
    data:
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 100Mi
      globalMounts:
        - path: /databasus-data
