database:
  image:
    registry: ghcr.io
    repository: cloudnative-pg/postgresql
    tag: 17

  clusterName: postiz
  logLevel: error
  replicas: 1
  size: 1Gi

  monitoring:
    enabled: false

  backups:
    enabled: false
    secretName: ''
    retention: ''
    path: ''
    endpoint: ''

  topologySpreadConstraints:

app-template:
  controllers:
    postiz:
      strategy: Recreate
      containers:
        main:
          image:
            repository: ghcr.io/gitroomhq/postiz-app
            tag: v2.6.0
            pullPolicy: IfNotPresent
          env:
            MAIN_URL: "https://postiz.cloud.obara.xyz"
            FRONTEND_URL: "https://postiz.cloud.obara.xyz"
            NEXT_PUBLIC_BACKEND_URL: "https://postiz.cloud.obara.xyz/api"
            BACKEND_INTERNAL_URL: "http://localhost:3000"
            STORAGE_PROVIDER: "local"
            UPLOAD_DIRECTORY: "/uploads"
            DISABLE_REGISTRATION: "true"
            REDIS_URL:
              valueFrom:
                secretKeyRef:
                  name: postiz-cache-secret
                  key: host
            DATABASE_URL:
              valueFrom:
                secretKeyRef:
                  name: postiz-app
                  key: uri
            JWT_SECRET:
              valueFrom:
                secretKeyRef:
                  name: postiz-jwt-secret
                  key: jwt-secret

  service:
    postiz:
      controller: postiz
      ports:
        http:
          port: 5000

  ingress:
    postiz:
      annotations: {}
      hosts:
        - host: postiz.cloud.obara.xyz
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: postiz
                port: http

  persistence:
    postiz:
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /uploads

cache:
  clusterName: postiz


#JWT_SECRET not set.                                                                                                 │
#STORAGE_PROVIDER not set. Needed to setup storage.