apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: forgejo-shell
spec:
  entryPoints:
  - forgejo-ssh
  routes:
  - match: HostSNI(`*`)
    services:
    - name: forgejo-ssh
      namespace: development
      port: 2222
