apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: forgejo-ssh
  namespace: development
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
  - forgejo-ssh
  routes:
  - match: HostSNI(`*`)
    services:
    - name: forgejo-ssh
      port: 2222
