apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-client-externalsecrets
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: oracle-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-client-secrets
  data:
  - secretKey: keycloak-client-id
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: development/forgejo
      property: keycloak-client-id
  - secretKey: keycloak-client-secret
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: development/forgejo
      property: keycloak-client-secret