cert-manager:
  crds:
    enabled: true
    keep: false
  enableCertificateOwnerRef: true
  dns01RecursiveNameservers: 1.1.1.1:53,8.8.8.8:53

externalSecrets:
  secretStoreRef:
    name: oracle-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-token-secret
  data:
    - secretKey: cloudflare-token
      remoteRef:
        key: cluster/cloudflare
        property: cloudflare-token
