haven:
  ingress:
    enabled: false

  service:
    annotations:
      traefik.ingress.kubernetes.io/service.serversscheme: https

  haven:
    host: "0.0.0.0"
    server_name: "Chat"
    admin_user: "superadmin"

  image:
    repository: ghcr.io/ancsemi/haven
    tag: 4.12.0
