apiVersion: v2
name: tuwunel
version: 1.0.0

sources:
  - https://github.com/matrix-construct/tuwunel

dependencies:
  - name: tuwunel
    repository: https://github.com/AreYouLoco/tuwunel-helm/
    version: 0.1.1
