# tuwunel:
image:
  tag: v1.5.0

config:
  server_name: "matrix.cloud.obara.xyz"
  max_request_size: "20000000"
  allow_registration: trued
  # You must set registration token below to enable registrations
  registration_token: "supa-dupa-secret-token"
  allow_federation: false
  trusted_servers: []

extraEnv: []

## Add additional labels to all resources
extraLabels: {}


ingress:
  enabled: true
  class: "traefik"
  annotations: {}
  path: /
  hosts:
    - "matrix.cloud.obara.xyz"
  tls: false

## Persist configuration to a persistent volume
persistence:
  ## Data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If unset, storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  data:
    enabled: true
    existingClaim:
    storageClass:
    accessMode: ReadWriteOnce
    size: 16Gi
