database:
  image:
    registry: ghcr.io
    repository: cloudnative-pg/postgresql
    tag: 17

  clusterName: forgejo
  logLevel: error
  replicas: 1
  size: 10Gi

  monitoring:
    enabled: false

  backups:
    enabled: false
    secretName: ''
    retention: ''
    path: ''
    endpoint: ''

  topologySpreadConstraints:

cache:
  clusterName: forgejo

forgejo:
  service:
    ssh:
      port: 2222

  global:
    storageClass: 'longhorn'

  ingress:
    enabled: true
    className: traefik
    annotations: {}
    hosts:
      - host: git.cloud.obara.xyz
        paths:
          - path: /
            pathType: Prefix
            port: http

  deployment:
    env: []
      # - name: VARIABLE
      #   value: my-value
    terminationGracePeriodSeconds: 60
    labels: {}
    annotations: {}

  serviceAccount:
    create: false
    name: ''
    automountServiceAccountToken: false
    imagePullSecrets: []
    # - name: private-registry-access
    annotations: {}
    labels: {}

  persistence:
    enabled: true
    create: true
    mount: true
    claimName: gitea-shared-storage
    size: 10Gi
    accessModes:
      - ReadWriteOnce
    labels: {}
    storageClass:
    subPath:
    volumeName: ''
    annotations:
      helm.sh/resource-policy: keep

  signing:
    enabled: false
    gpgHome: /data/git/.gnupg
    privateKey: ''
    # privateKey: |-
    #   -----BEGIN PGP PRIVATE KEY BLOCK-----
    #   ...
    #   -----END PGP PRIVATE KEY BLOCK-----
    existingSecret: ''

  ## @section Gitea
  #
  gitea:
    ## @param gitea.admin.username Username for the Forgejo admin user
    ## @param gitea.admin.existingSecret Use an existing secret to store admin user credentials
    ## @param gitea.admin.password Password for the Forgejo admin user
    ## @param gitea.admin.email Email for the Forgejo admin user
    ## @param gitea.admin.passwordMode Mode for how to set/update the admin user password. Options are: initialOnlyNoReset, initialOnlyRequireReset, and keepUpdated
    admin:
      existingSecret: forgejo-admin-secret
      # existingSecret:
      # username: gitea_admin
      # password: r8sA8CPHD9!bt6d
      # email: 'gitea@local.domain'
      # passwordMode: keepUpdated

    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
        namespace: ''

    # Either specify inline `key` and `secret` or refer to them via `existingSecret`
    ## @param gitea.oauth OAuth configuration
    oauth: []
      # - name: 'OAuth 1'
      #   provider:
      #   key:
      #   secret:
      #   existingSecret:
      #   autoDiscoverUrl:
      #   useCustomUrls:
      #   customAuthUrl:
      #   customTokenUrl:
      #   customProfileUrl:
      #   customEmailUrl:

    ## @param gitea.additionalConfigSources Additional configuration from secret or configmap
    additionalConfigSources: []
    #   - secret:
    #       secretName: gitea-app-ini-oauth
    #   - configMap:
    #       name: gitea-app-ini-plaintext

    ## @param gitea.additionalConfigFromEnvs Additional configuration sources from environment variables
    # additionalConfigFromEnvs: []
    additionalConfigFromEnvs:
      - name: FORGEJO__DATABASE__PASSWD
        valueFrom:
          secretKeyRef:
            name: forgejo-app
            key: password
      - name: FORGEJO__DATABASE__USER
        valueFrom:
          secretKeyRef:
            name: forgejo-app
            key: username
      - name: FORGEJO__DATABASE__NAME
        valueFrom:
          secretKeyRef:
            name: forgejo-app
            key: dbname
      - name: FORGEJO__DATABASE__HOST
        valueFrom:
          secretKeyRef:
            name: forgejo-app
            key: host
      - name: FORGEJO__CACHE__HOST
        valueFrom:
          secretKeyRef:
            name: forgejo-cache-secret
            key: host

    ## @section `app.ini` overrides
    ## @descriptionStart
    ## Every value described in the [Cheat
    ## Sheet](https://forgejo.org/docs/latest/admin/config-cheat-sheet/) can be
    ## set as a Helm value. Configuration sections map to (lowercased) YAML
    ## blocks, while the keys themselves remain in all caps.
    ## @descriptionEnd
    config:
      # values in the DEFAULT section
      # (https://forgejo.org/docs/latest/admin/config-cheat-sheet/#overall-default)
      # are un-namespaced

      ## @param gitea.config.APP_NAME Application name, used in the page title
      APP_NAME: 'Forgejo: Beyond coding. We forge.'

      ## @param gitea.config.RUN_MODE Application run mode, affects performance and debugging: `dev` or `prod`
      RUN_MODE: prod

      ## @param gitea.config.repository General repository settings
      repository: {}

      ## @param gitea.config.cors Cross-origin resource sharing settings
      cors: {}

      ## @param gitea.config.ui User interface settings
      ui: {}

      ## @param gitea.config.markdown Markdown parser settings
      markdown: {}

      ## @param gitea.config.server [object] General server settings
      server:
        SSH_PORT: 2222 # rootful image
        SSH_LISTEN_PORT: 2222 # rootless image
        ROOT_URL: https://git.cloud.obara.xyz/
        ENABLE_PASSWORD_SIGNIN_FORM: false

      ## @param gitea.config.database Database configuration (only necessary with an [externally managed DB](https://code.forgejo.org/forgejo-helm/forgejo-helm#external-database)).
      database:
        DB_TYPE: postgres
        SCHEMA: gitea
      ## @param gitea.config.indexer Settings for what content is indexed and how
      indexer: {}

      ## @param gitea.config.queue Job queue configuration
      queue: {}

      ## @param gitea.config.admin Admin user settings
      admin: {}

      ## @param gitea.config.security Site security settings
      security: {}

      ## @param gitea.config.camo Settings for the [camo](https://github.com/cactus/go-camo) media proxy server (disabled by default)
      camo: {}

      ## @param gitea.config.openid Configuration for authentication with OpenID (disabled by default)
      openid:
        ENABLE_OPENID_SIGNUP: true

      ## @param gitea.config.oauth2_client OAuth2 client settings
      oauth2_client: {}

      ## @param gitea.config.service Configuration for miscellaneous Forgejo services
      service:
        DISABLE_REGISTRATION: true
        ENABLE_BASIC_AUTHENTICATION: true
        ENABLE_INTERNAL_SIGNIN: true

      ## @param gitea.config.ssh.minimum_key_sizes SSH minimum key sizes
      ssh.minimum_key_sizes: {}

      ## @param gitea.config.webhook Webhook settings
      webhook: {}

      ## @param gitea.config.mailer Mailer configuration (disabled by default)
      mailer: {}

      ## @param gitea.config.email.incoming Configuration for handling incoming mail (disabled by default)
      email.incoming: {}

      ## @param gitea.config.cache Cache configuration
      cache: {}

      ## @param gitea.config.session Session/cookie handling
      session: {}

      ## @param gitea.config.picture User avatar settings
      picture: {}

      ## @param gitea.config.project Project board defaults
      project: {}

      ## @param gitea.config.attachment Issue and PR attachment configuration
      attachment: {}

      ## @param gitea.config.log Logging configuration
      log: {}

      ## @param gitea.config.cron Cron job configuration
      cron: {}

      ## @param gitea.config.git Global settings for Git
      git: {}

      ## @param gitea.config.metrics Settings for the Prometheus endpoint (disabled by default)
      metrics: {}

      ## @param gitea.config.api Settings for the Swagger API documentation endpoints
      api: {}

      ## @param gitea.config.oauth2 Settings for the [OAuth2 provider](https://forgejo.org/docs/latest/admin/oauth2-provider/)
      oauth2: {}

      ## @param gitea.config.i18n Internationalization settings
      i18n: {}

      ## @param gitea.config.markup Configuration for advanced markup processors
      markup: {}

      ## @param gitea.config.highlight.mapping File extension to language mapping overrides for syntax highlighting
      highlight.mapping: {}

      ## @param gitea.config.time Locale settings
      time: {}

      ## @param gitea.config.migrations Settings for Git repository migrations
      migrations: {}

      ## @param gitea.config.federation Federation configuration
      federation: {}

      ## @param gitea.config.packages Package registry settings
      packages: {}

      ## @param gitea.config.mirror Configuration for repository mirroring
      mirror: {}

      ## @param gitea.config.lfs Large File Storage configuration
      lfs: {}

      ## @param gitea.config.repo-avatar Repository avatar storage configuration
      repo-avatar: {}

      ## @param gitea.config.avatar User/org avatar storage configuration
      avatar: {}

      ## @param gitea.config.storage General storage settings
      storage: {}

      ## @param gitea.config.proxy Proxy configuration (disabled by default)
      proxy: {}

      ## @param gitea.config.actions Configuration for [Forgejo Actions](https://forgejo.org/docs/latest/user/actions/)
      actions: {}

      ## @param gitea.config.other Uncategorized configuration options
      other: {}

  valkey-cluster:
    enabled: false

  postgresql-ha:
    enabled: false
