
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: kube-system
spec:
  interval: 1m
  url: https://stefanprodan.github.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: podinfo
      version: '6.9.1'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
  values:
    ingress:
      enabled: true
      className: "traefik"
      additionalLabels: {}
      annotations: {}
      hosts:
        - host: podinfo.cloud.obara.xyz
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: 
        - secretName: cloud-obara-dev-tls
          hosts:
            - podinfo.cloud.obara.xyz
