newt:
  global:
    image:
      tag: 1.13.0
      digest: sha256:63d956c8fdee889255e441ec405193b47b1fd2d975b505492ec848a8007f4fc3
  newtInstances:
    - name: "oracle-cluster-tunnel"
      enabled: true
      auth:
        existingSecretName: "newt-secrets"

externalSecrets:
  secretStoreRef:
    name: oracle-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: newt-secrets
  data:
  - secretKey: PANGOLIN_ENDPOINT
    remoteRef:
      key: cluster/newt
      property: PANGOLIN_ENDPOINT
  - secretKey: NEWT_ID
    remoteRef:
      key: cluster/newt
      property: NEWT_ID
  - secretKey: NEWT_SECRET
    remoteRef:
      key: cluster/newt
      property: NEWT_SECRET
