gatus:
  image:
    repository: "ghcr.io/twin/gatus"
    tag: "v5.20.0"
  ingress:
    enabled: true
    ingressClassName: "traefik"
    hosts:
    - status.cloud.obara.xyz

  secrets: false

  config:
    endpoints:
      - name: PodInfo
        url: "http://podinfo.default.svc.cluster.local:9898"
        conditions:
          - "[STATUS] == 200"
      - name: PocketId
        url: "http://pocketid.default.svc.cluster.local:1411"
        conditions:
          - "[STATUS] == 200"
      - name: Mattermost
        url: http://mm.obara.dev/api/v4/system/ping
        group: Services
        interval: 1m
        conditions:
          - "[STATUS] == 200"
          - "[BODY].status == OK"
        client:
          dns-resolver: "tcp://192.168.10.10:53"
    storage:
      type: postgres
      path: "${POSTGRES_FQDN}?sslmode=disable"
    security:
      oidc:
        issuer-url: "https://id.cloud.obara.xyz"
        redirect-url: "https://status.cloud.obara.xyz/authorization-code/callback"
        client-id: "${OIDC_ID}"
        client-secret: "${OIDC_SECRET}"
        scopes: ["openid"]
        allowed-subjects: ["${ALLOWED_SUBJECTS}"]
  env: 
    POSTGRES_FQDN:
      valueFrom:
        secretKeyRef:
          name: gatus-app
          key: fqdn-uri
    OIDC_ID:
      valueFrom:
        secretKeyRef:
          name: gatus-secrets
          key: client_id
    OIDC_SECRET:
      valueFrom:
        secretKeyRef:
          name: gatus-secrets
          key: client_secret
    ALLOWED_SUBJECTS:
      valueFrom:
        secretKeyRef:
          name: gatus-secrets
          key: allowed_subjects

database:
  image:
    registry: ghcr.io
    repository: cloudnative-pg/postgresql
    tag: 17

  clusterName: gatus
  logLevel: error
  replicas: 1
  size: 500Mi

  monitoring:
    enabled: false

  backups:
    enabled: false
    secretName: ''
    retention: ''
    path: ''
    endpoint: ''

  topologySpreadConstraints: