apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-externalsecret
spec:
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: test-secret
  data:
    - secretKey: TEST_KEY
      remoteRef:
        key: FOO