---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-labs
  namespace: kube-system
spec:
  interval: 1m
  url: https://bitnami-labs.github.io/sealed-secrets/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: sealed-secrets
      version: '2.17.3'
      sourceRef:
        kind: HelmRepository
        name: bitnami-labs
        namespace: kube-system
      interval: 10m
  values: 
    fullnameOverride: "sealed-secrets-controller"
